### ISSUE TITLE
Sponsors view is broken in provided CSS

### ISSUE THREAD

**Issue by polybuildr** [felicity-iiith/felicity16-website-teaser#1]

**Comment by hharchani** [comment]
Any image for this? What's broken?

**Comment by polybuildr** [comment]
Sorry, rather bad bug report. I'll post a screenshot in a minute.

**Comment by polybuildr** [comment]
Here's a screenshot taken using Chromium (Version 45.0.2454.101 Ubuntu 14.04 (64-bit))
![broken-sponsors](https://cloud.githubusercontent.com/assets/6189009/10358833/0a2a8410-6db0-11e5-8be3-6ad3ca989369.png)

**Comment by polybuildr** [comment]
The `.col`s are too narrow, and so the images just overflow.

**Comment by hharchani** [comment]
Not relevant.
